import { env } from "@/server/env";
import { SmtpEmailTransport } from "@/server/email/smtp";
import { isSuppressed } from "@/server/email/suppression";

/**
 * Outbound email behind an adapter.
 *
 * Two implementations. The default writes the message, including the
 * verification/reset link, to the server log, which makes the whole
 * verification and password-reset flow genuinely usable in development instead
 * of being a dead end. Setting `EMAIL_PROVIDER=smtp` switches to real delivery;
 * see `smtp.ts` for why SMTP rather than a provider SDK.
 */

export interface EmailMessage {
  to: string;
  subject: string;
  /**
   * The plain-text part. Required, not optional, and never generated by
   * stripping tags out of `html`: a message with no text part is scored as
   * spam by most filters, and the readers who see it are the ones on a screen
   * reader or a terminal client. `email/templates.ts` produces both parts from
   * one description so they cannot disagree.
   */
  text: string;
  /** The branded part. Absent for anything sent outside the templates. */
  html?: string;
  /**
   * Where this person goes to make it stop.
   *
   * Set on bulk and notification mail, and deliberately *not* on verification
   * or password-reset mail: those are not a subscription, there is nothing to
   * unsubscribe from, and offering it on a password reset invites somebody
   * locked out of their account to opt out of the only message that can let
   * them back in. Present, it becomes the `List-Unsubscribe` headers.
   */
  unsubscribeUrl?: string;
}

export interface EmailTransport {
  send(message: EmailMessage): Promise<void>;
}

class ConsoleEmailTransport implements EmailTransport {
  async send(message: EmailMessage): Promise<void> {
    console.info(
      [
        "",
        "──────────── email (console transport) ────────────",
        `from:    ${env().EMAIL_FROM}`,
        `to:      ${message.to}`,
        `subject: ${message.subject}`,
        // The text part is what gets printed: it is the readable one in a
        // terminal, and it carries the same link. The HTML part is noted
        // rather than dumped, several hundred lines of tables would bury the
        // verification link this transport exists to surface. To look at the
        // rendered thing, use the previews under /admin/brand.
        message.html ? `parts:   text + html (${message.html.length} bytes)` : "",
        "",
        message.text,
        "───────────────────────────────────────────────────",
        "",
      ].join("\n"),
    );
  }
}

let override: EmailTransport | undefined;

/** Test seam. */
export function setEmailTransport(next: EmailTransport | undefined) {
  override = next;
}

export function transport(): EmailTransport {
  if (override) return override;
  return env().EMAIL_PROVIDER === "smtp"
    ? new SmtpEmailTransport()
    : new ConsoleEmailTransport();
}

/**
 * The one door out.
 *
 * The suppression check lives here rather than in each caller, because "each
 * caller" is the arrangement where the next feature to send an email forgets.
 * It is a single indexed lookup on an address we already have in hand.
 *
 * It is *not* wrapped in a try/catch that sends anyway. If the database is
 * unreachable the correct behaviour is to fail this send, the caller for a
 * notification already swallows the error, and the caller for a password reset
 * already surfaces it. Sending to an address we cannot check is how a
 * suppression list quietly stops meaning anything.
 */
export async function sendEmail(message: EmailMessage): Promise<void> {
  if (await isSuppressed(message.to)) {
    // Not an error. The address is genuinely undeliverable, the caller did
    // nothing wrong, and there is nothing for it to do about it.
    return;
  }
  await transport().send(message);
}
